/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void setpointSlider_change1(GCustomSlider source, GEvent event) { //_CODE_:setpointSlider:541758:
  setpoint = setpointSlider.getValueI();
  
  
} //_CODE_:setpointSlider:541758:

public void kpTextfield_change(GTextField source, GEvent event) { //_CODE_:kpTextfield:369426:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:kpTextfield:369426:

public void kiTextfield_change(GTextField source, GEvent event) { //_CODE_:kiTextfield:870370:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:kiTextfield:870370:

public void kdTextfield_change(GTextField source, GEvent event) { //_CODE_:kdTextfield:979035:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:kdTextfield:979035:

public void option3_clicked1(GOption source, GEvent event) { //_CODE_:option3:556855:
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:option3:556855:

public void option4_clicked1(GOption source, GEvent event) { //_CODE_:option4:705268:
  println("option4 - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:option4:705268:

public void updateButton_click(GButton source, GEvent event) { //_CODE_:updateButton:434548:
  pid.setTunings( float(kpTextfield.getText()),
                  float(kiTextfield.getText()),
                  float(kdTextfield.getText()) );
} //_CODE_:updateButton:434548:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  setpointSlider = new GCustomSlider(this, 460, 30, 320, 70, "grey_blue");
  setpointSlider.setShowValue(true);
  setpointSlider.setShowLimits(true);
  setpointSlider.setTextOrientation(G4P.ORIENT_LEFT);
  setpointSlider.setRotation(PI/2, GControlMode.CORNER);
  setpointSlider.setLimits(0, 100, 0);
  setpointSlider.setNumberFormat(G4P.INTEGER, 0);
  setpointSlider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  setpointSlider.setOpaque(false);
  setpointSlider.addEventHandler(this, "setpointSlider_change1");
  label8 = new GLabel(this, 20, 30, 80, 20);
  label8.setText("SIMULAÇÃO");
  label8.setTextBold();
  label8.setOpaque(false);
  label9 = new GLabel(this, 20, 60, 80, 20);
  label9.setText("Setpoint");
  label9.setOpaque(false);
  label10 = new GLabel(this, 120, 60, 80, 20);
  label10.setText("Entrada");
  label10.setOpaque(false);
  label11 = new GLabel(this, 220, 60, 80, 20);
  label11.setText("Saída");
  label11.setOpaque(false);
  label12 = new GLabel(this, 320, 60, 80, 20);
  label12.setText("Erro");
  label12.setOpaque(false);
  label13 = new GLabel(this, 20, 180, 300, 20);
  label13.setText("PARÂMETROS DO CONTROLADOR");
  label13.setTextBold();
  label13.setOpaque(false);
  label14 = new GLabel(this, 20, 210, 80, 20);
  label14.setText("Kp");
  label14.setOpaque(false);
  label15 = new GLabel(this, 160, 210, 80, 20);
  label15.setText("Ki");
  label15.setOpaque(false);
  label16 = new GLabel(this, 290, 210, 80, 20);
  label16.setText("Kd");
  label16.setOpaque(false);
  kpTextfield = new GTextField(this, 20, 240, 80, 30, G4P.SCROLLBARS_NONE);
  kpTextfield.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  kpTextfield.setOpaque(true);
  kpTextfield.addEventHandler(this, "kpTextfield_change");
  kiTextfield = new GTextField(this, 160, 240, 80, 30, G4P.SCROLLBARS_NONE);
  kiTextfield.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  kiTextfield.setOpaque(true);
  kiTextfield.addEventHandler(this, "kiTextfield_change");
  kdTextfield = new GTextField(this, 290, 240, 80, 30, G4P.SCROLLBARS_NONE);
  kdTextfield.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  kdTextfield.setOpaque(true);
  kdTextfield.addEventHandler(this, "kdTextfield_change");
  togGroup1 = new GToggleGroup();
  option3 = new GOption(this, 20, 310, 120, 20);
  option3.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option3.setText("Manual");
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  option4 = new GOption(this, 20, 330, 120, 20);
  option4.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option4.setText("Automático");
  option4.setOpaque(false);
  option4.addEventHandler(this, "option4_clicked1");
  togGroup1.addControl(option3);
  option3.setSelected(true);
  togGroup1.addControl(option4);
  label17 = new GLabel(this, 20, 290, 120, 20);
  label17.setText("Modo de Operação");
  label17.setTextBold();
  label17.setOpaque(false);
  updateButton = new GButton(this, 290, 320, 80, 30);
  updateButton.setText("Atualizar");
  updateButton.setTextBold();
  updateButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  updateButton.addEventHandler(this, "updateButton_click");
  spLabel = new GLabel(this, 20, 90, 80, 20);
  spLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  spLabel.setText("spLabel");
  spLabel.setTextItalic();
  spLabel.setOpaque(false);
  inputLabel = new GLabel(this, 120, 90, 80, 20);
  inputLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  inputLabel.setText("inputLabel");
  inputLabel.setOpaque(false);
  outputLabel = new GLabel(this, 220, 90, 80, 20);
  outputLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  outputLabel.setText("outputLabel");
  outputLabel.setOpaque(false);
  errorLabel = new GLabel(this, 320, 90, 80, 20);
  errorLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  errorLabel.setText("errorLabel");
  errorLabel.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider setpointSlider; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GLabel label11; 
GLabel label12; 
GLabel label13; 
GLabel label14; 
GLabel label15; 
GLabel label16; 
GTextField kpTextfield; 
GTextField kiTextfield; 
GTextField kdTextfield; 
GToggleGroup togGroup1; 
GOption option3; 
GOption option4; 
GLabel label17; 
GButton updateButton; 
GLabel spLabel; 
GLabel inputLabel; 
GLabel outputLabel; 
GLabel errorLabel; 
